#!/bin/bash
# Script para organizar fotos de LUCULUC

set -e

echo "🌿 LUCULUC Image Setup"
echo "======================================"
echo ""
echo "Este script te ayuda a organizar las fotos de LUCULUC"
echo ""
echo "Estructura de carpetas esperada:"
echo ""
echo "public/images/"
echo "├── hero-bg.jpg                    # Portada principal (1920x1080 mín)"
echo "├── og-image.jpg                   # Open Graph (1200x630)"
echo "├── favicon.ico                    # Ícono del sitio"
echo "│"
echo "├── rooms/"
echo "│   ├── master.jpg                 # Habitación principal (King)"
echo "│   ├── secondary-1.jpg            # Habitación secundaria 1 (Queen)"
echo "│   └── secondary-2.jpg            # Habitación secundaria 2 (Queen)"
echo "│"
echo "├── experiences/"
echo "│   ├── arenal.jpg                 # Volcán Arenal"
echo "│   ├── catarata-fortuna.jpg       # Catarata La Fortuna"
echo "│   ├── termales.jpg               # Aguas termales"
echo "│   ├── ciudad-quesada.jpg         # Ciudad Quesada"
echo "│   ├── senderos.jpg               # Senderos & naturaleza"
echo "│   └── aventura.jpg               # Tours de aventura"
echo ""
echo "======================================"
echo ""
echo "📝 INSTRUCCIONES:"
echo ""
echo "1. Descarga tu carpeta de Google Drive:"
echo "   https://drive.google.com/drive/folders/1xCloHFOsv50FQp8oZ-NHm3Tn9MeOVKIR"
echo ""
echo "2. Selecciona las fotos y COMPRIME:"
echo "   - Máximo 1200px de ancho"
echo "   - Calidad 80-85%"
echo "   - Formato: JPG o WebP"
echo ""
echo "3. Copia las fotos a las carpetas indicadas arriba"
echo ""
echo "4. Verifica que compilen:"
echo "   npm run build"
echo ""
echo "5. Optimización automática:"
echo "   El sitio usa next/image, que optimiza automáticamente"
echo ""
echo "======================================"
echo "✅ Listo para copiar imágenes"
